### ISSUE TITLE
Excel refuser alors qu'il a le features 

### ISSUE THREAD

**Issue by clothilde-ferreira** [brainhack-ch/piriform-cortex-diversity#26]
Hello,

je viens d'extraire toute les excel avec l'ancienne version de imaris pour retrouver les classe apical et basal.
J'ai 13 neurones sur les 115 qui ne passe pas. 
Je ne comprend pas pourquoi, car les features sont presents et il me le détecte pas. 
Les 13 ont exactement le meme message 

<img width="1712" alt="Capture d’écran 2023-03-11 à 20 12 00" src="https://user-images.githubusercontent.com/119606166/224507356-f43ff7b0-ea3a-41ee-a81f-767d82905321.png">

**Comment by clothilde-ferreira** [comment]
je viens de trouver une solution mais je ne peux pas effacer le message temps qu'il n'est pas classer :)

**Comment by hugofluhr** [comment]
Est-ce que tu peux nous dire comment tu as réglé le problème?

**Comment by clothilde-ferreira** [comment]
oui j'ai simplement changer le nom de la fiche dans on excel qui poser problème. 
Je ne sais pas pourquoi mais pour ces fichiers le nom des features était bon mais sur la feuille du excel en bas il manquait le mot "dendrite" donc je l'ai mis a la main .

**Comment by hugofluhr** [comment]
très bien, je vais essayer de rendre le code un peu plus robuste à ce genre de choses dans les changements que je fais pour #23 mais certainement qu'il y aura encore des cas qu'il faudra corriger "à la main".
